root: true
env:
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2019
  sourceType: module
  project: tsconfig.json
plugins:
  - "@typescript-eslint"
extends:
  - standard
  - plugin:@typescript-eslint/recommended
rules:
  max-len:
    - error
    - code: 120
  comma-dangle:
    - error
    - always-multiline
